name: CI/CD GitHub Actions

on:
  push:
    branches: 
      - master
  pull_request:
    branches: [ master ]
    types: [opened, synchronize, reopened]

jobs:

  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-tk python3-dev
        sudo apt-get install -y xvfb
        python -m pip install --upgrade pip
        pip install coverage
        pip install pillow

    - name: Invalidate cache
      run: |
       git checkout HEAD -- .github/workflows
       git pull

    - name: Run tests and collect coverage
      run: |
       export DISPLAY=:99
       Xvfb :99 -ac &
       ps -ef | grep Xvfb
       pwd
       ls -l App/tests/
       coverage run --omit=App --source=App -m unittest discover -s App
      env:
       DISPLAY: ":99"
       
    - name: Install coveralls
      run: |
        python -m pip install --upgrade pip
        pip install coveralls

    - name: Upload coverage to Coveralls
      env:
       COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: coveralls

    - name: Force update Coveralls badge
      run: curl https://coveralls.io/webhook?repo_token=${{ secrets.COVERALLS_REPO_TOKEN }} -d "payload[status]=done"

  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env: 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


